//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoSI2EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class activo_preçocomercial
    {
        public int id_activo { get; set; }
        public double preco { get; set; }
        public System.DateTime data_alteracao { get; set; }
    
        public virtual activo activo { get; set; }
    }
}
