//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoSI2EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class activo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public activo()
        {
            this.activo_preçocomercial = new HashSet<activo_preçocomercial>();
            this.intervencaos = new HashSet<intervencao>();
            this.activo1 = new HashSet<activo>();
            this.activoes = new HashSet<activo>();
            this.funcionarios = new HashSet<funcionario>();
        }
    
        public int activo_id { get; set; }
        public string nome { get; set; }
        public System.DateTime data_aquisicao { get; set; }
        public bool estado { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public Nullable<int> tipo { get; set; }
    
        public virtual tipo_activo tipo_activo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activo_preçocomercial> activo_preçocomercial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<intervencao> intervencaos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activo> activo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<activo> activoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<funcionario> funcionarios { get; set; }
    }
}
