//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoSI2EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Project1Entities : DbContext
    {
        public Project1Entities()
            : base("name=Project1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activo> activoes { get; set; }
        public virtual DbSet<activo_preçocomercial> activo_preçocomercial { get; set; }
        public virtual DbSet<competencia> competencias { get; set; }
        public virtual DbSet<equipa> equipas { get; set; }
        public virtual DbSet<funcionario> funcionarios { get; set; }
        public virtual DbSet<intervencao> intervencaos { get; set; }
        public virtual DbSet<intervencao_equipa> intervencao_equipa { get; set; }
        public virtual DbSet<tipo_activo> tipo_activo { get; set; }
        public virtual DbSet<IntervencoesPorEquipa> IntervencoesPorEquipas { get; set; }
        public virtual DbSet<vw_Resumo_Intervencao> vw_Resumo_Intervencao { get; set; }
    
        [DbFunction("Project1Entities", "f_listIntervention")]
        public virtual IQueryable<f_listIntervention_Result> f_listIntervention(Nullable<int> id_intervencao, Nullable<int> year)
        {
            var id_intervencaoParameter = id_intervencao.HasValue ?
                new ObjectParameter("id_intervencao", id_intervencao) :
                new ObjectParameter("id_intervencao", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_listIntervention_Result>("[Project1Entities].[f_listIntervention](@id_intervencao, @year)", id_intervencaoParameter, yearParameter);
        }
    
        [DbFunction("Project1Entities", "f_listInterventionsOfYear")]
        public virtual IQueryable<f_listInterventionsOfYear_Result> f_listInterventionsOfYear(Nullable<int> ano)
        {
            var anoParameter = ano.HasValue ?
                new ObjectParameter("ano", ano) :
                new ObjectParameter("ano", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<f_listInterventionsOfYear_Result>("[Project1Entities].[f_listInterventionsOfYear](@ano)", anoParameter);
        }
    
        public virtual int p_actualizaInformacaoFuncionario(Nullable<int> id_funcionario, string endereco, string profissao, Nullable<int> telefone, string email)
        {
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            var enderecoParameter = endereco != null ?
                new ObjectParameter("endereco", endereco) :
                new ObjectParameter("endereco", typeof(string));
    
            var profissaoParameter = profissao != null ?
                new ObjectParameter("profissao", profissao) :
                new ObjectParameter("profissao", typeof(string));
    
            var telefoneParameter = telefone.HasValue ?
                new ObjectParameter("telefone", telefone) :
                new ObjectParameter("telefone", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_actualizaInformacaoFuncionario", id_funcionarioParameter, enderecoParameter, profissaoParameter, telefoneParameter, emailParameter);
        }
    
        public virtual int p_adicionarCompetencias(Nullable<int> id_funcionario, Nullable<int> id_competencia)
        {
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            var id_competenciaParameter = id_competencia.HasValue ?
                new ObjectParameter("id_competencia", id_competencia) :
                new ObjectParameter("id_competencia", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_adicionarCompetencias", id_funcionarioParameter, id_competenciaParameter);
        }
    
        public virtual int p_adicionarElementoEquipa(Nullable<int> id_equipa, Nullable<int> id_funcionario)
        {
            var id_equipaParameter = id_equipa.HasValue ?
                new ObjectParameter("id_equipa", id_equipa) :
                new ObjectParameter("id_equipa", typeof(int));
    
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_adicionarElementoEquipa", id_equipaParameter, id_funcionarioParameter);
        }
    
        public virtual int p_criaEquipa(string localizacao, Nullable<int> id_supervisor)
        {
            var localizacaoParameter = localizacao != null ?
                new ObjectParameter("localizacao", localizacao) :
                new ObjectParameter("localizacao", typeof(string));
    
            var id_supervisorParameter = id_supervisor.HasValue ?
                new ObjectParameter("id_supervisor", id_supervisor) :
                new ObjectParameter("id_supervisor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_criaEquipa", localizacaoParameter, id_supervisorParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> p_criaIntervencao(Nullable<int> id_activo, string descricao, Nullable<double> valor, Nullable<System.DateTime> data_inicio, Nullable<System.DateTime> data_fim)
        {
            var id_activoParameter = id_activo.HasValue ?
                new ObjectParameter("id_activo", id_activo) :
                new ObjectParameter("id_activo", typeof(int));
    
            var descricaoParameter = descricao != null ?
                new ObjectParameter("descricao", descricao) :
                new ObjectParameter("descricao", typeof(string));
    
            var valorParameter = valor.HasValue ?
                new ObjectParameter("valor", valor) :
                new ObjectParameter("valor", typeof(double));
    
            var data_inicioParameter = data_inicio.HasValue ?
                new ObjectParameter("data_inicio", data_inicio) :
                new ObjectParameter("data_inicio", typeof(System.DateTime));
    
            var data_fimParameter = data_fim.HasValue ?
                new ObjectParameter("data_fim", data_fim) :
                new ObjectParameter("data_fim", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("p_criaIntervencao", id_activoParameter, descricaoParameter, valorParameter, data_inicioParameter, data_fimParameter);
        }
    
        public virtual int p_eliminarEquipa(Nullable<int> id_equipa)
        {
            var id_equipaParameter = id_equipa.HasValue ?
                new ObjectParameter("id_equipa", id_equipa) :
                new ObjectParameter("id_equipa", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_eliminarEquipa", id_equipaParameter);
        }
    
        public virtual int p_inserirFuncionario(Nullable<int> numero_identificacao, string nome, Nullable<System.DateTime> data_nascimento, string endereco, string profissao, Nullable<int> telefone, string email)
        {
            var numero_identificacaoParameter = numero_identificacao.HasValue ?
                new ObjectParameter("numero_identificacao", numero_identificacao) :
                new ObjectParameter("numero_identificacao", typeof(int));
    
            var nomeParameter = nome != null ?
                new ObjectParameter("nome", nome) :
                new ObjectParameter("nome", typeof(string));
    
            var data_nascimentoParameter = data_nascimento.HasValue ?
                new ObjectParameter("data_nascimento", data_nascimento) :
                new ObjectParameter("data_nascimento", typeof(System.DateTime));
    
            var enderecoParameter = endereco != null ?
                new ObjectParameter("endereco", endereco) :
                new ObjectParameter("endereco", typeof(string));
    
            var profissaoParameter = profissao != null ?
                new ObjectParameter("profissao", profissao) :
                new ObjectParameter("profissao", typeof(string));
    
            var telefoneParameter = telefone.HasValue ?
                new ObjectParameter("telefone", telefone) :
                new ObjectParameter("telefone", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_inserirFuncionario", numero_identificacaoParameter, nomeParameter, data_nascimentoParameter, enderecoParameter, profissaoParameter, telefoneParameter, emailParameter);
        }
    
        public virtual int p_removerElementoEquipa(Nullable<int> id_equipa, Nullable<int> id_funcionario)
        {
            var id_equipaParameter = id_equipa.HasValue ?
                new ObjectParameter("id_equipa", id_equipa) :
                new ObjectParameter("id_equipa", typeof(int));
    
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_removerElementoEquipa", id_equipaParameter, id_funcionarioParameter);
        }
    
        public virtual int p_removerFuncionario(Nullable<int> id_funcionario)
        {
            var id_funcionarioParameter = id_funcionario.HasValue ?
                new ObjectParameter("id_funcionario", id_funcionario) :
                new ObjectParameter("id_funcionario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_removerFuncionario", id_funcionarioParameter);
        }
    
        public virtual int p_updateInter(Nullable<int> id_intervencao, string estado)
        {
            var id_intervencaoParameter = id_intervencao.HasValue ?
                new ObjectParameter("id_intervencao", id_intervencao) :
                new ObjectParameter("id_intervencao", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_updateInter", id_intervencaoParameter, estadoParameter);
        }
    }
}
