//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoSI2EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class intervencao_equipa
    {
        public int codigo_equipa { get; set; }
        public int id_intervencao { get; set; }
        public System.DateTime data_inicio { get; set; }
    
        public virtual equipa equipa { get; set; }
        public virtual intervencao intervencao { get; set; }
    }
}
