//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoSI2EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntervencoesPorEquipa
    {
        public int codigo_equipa { get; set; }
        public int num_elems { get; set; }
        public Nullable<int> intervencoes_atribuidas { get; set; }
    }
}
