//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabalhoSI2EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Resumo_Intervencao
    {
        public int id_intervencao { get; set; }
        public string descricao { get; set; }
        public string estado { get; set; }
        public double valor { get; set; }
        public System.DateTime data_inicio { get; set; }
        public System.DateTime data_fim { get; set; }
        public string nome_activo { get; set; }
        public string marca_activo { get; set; }
        public string modelo_activo { get; set; }
    }
}
